import { RouteInfo } from "./sidebar.metadata";
export const ROUTES: RouteInfo[] = [
  {
    path: "",
    title: "-- Main",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "/dashboard/main",
    title: "Home",
    moduleName: "dashboard",
    iconType: "material-icons-two-tone",
    icon: "home",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },

  {
    path: "states",
    title: "States",
    moduleName: "states",
    iconType: "material-icons-two-tone",
    icon: "corporate_fare",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "postcodes",
    title: "Post Codes",
    moduleName: "postcodes",
    iconType: "material-icons-two-tone",
    icon: "all_inbox",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "categories",
    title: "Categories",
    moduleName: "categories",
    iconType: "material-icons-two-tone",
    icon: "category",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "sub_categories",
    title: "Sub Categories",
    moduleName: "sub_categories",
    iconType: "material-icons-two-tone",
    icon: "table_view",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "products",
    title: "Products",
    moduleName: "products",
    iconType: "material-icons-two-tone",
    icon: "shopping_bag",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "",
    title: "-- Admins",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "admins",
    title: "Admin Management",
    moduleName: "advance-table",
    iconType: "material-icons-two-tone",
    icon: "admin_panel_settings",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "users",
    title: "User Management",
    moduleName: "dashboard",
    iconType: "material-icons-two-tone",
    icon: "group",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },

  {
    path: "",
    title: "-- Reports",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "orders",
    title: "Orders",
    moduleName: "advance-table",
    iconType: "material-icons-two-tone",
    icon: "assignment",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "/dashboard/inquiry",
    title: "Inquiry",
    moduleName: "dashboard",
    iconType: "material-icons-two-tone",
    icon: "home",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
];
